version: '3.9'

services:
  pytorch:
    container_name: miyoshi_lung_cnn
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./:/src/app
      - /mnt/f/本データ三善用:/src/app/data
      - /mnt/f/ボクセルデータ979:/src/app/voxel_data979
      - /mnt/f/本ボクセルデータ:/src/app/voxel_data